#include "tvshow/app/builtin_themes.hpp"

namespace tvshow::app {

const char* k_css_tvision =
    "/* tvshow theme: tvision\n"
    " * Classic TurboVision look — cyan/yellow on dark blue, double borders.\n"
    " * Usage: <link rel=\"stylesheet\" href=\"/styles/tvision.css\">\n"
    " */\n"
    "\n"
    "/* ── base ──────────────────────────────────────────────────────── */\n"
    "body {\n"
    "  color: #ffff55;\n"
    "  background-color: #000080;\n"
    "  padding: 8px;\n"
    "}\n"
    "\n"
    "/* ── headings ──────────────────────────────────────────────────── */\n"
    "h1 { color: #55ffff; }\n"
    "h2 { color: #55ffff; }\n"
    "h3 { color: #55ffff; }\n"
    "\n"
    "/* ── links ─────────────────────────────────────────────────────── */\n"
    "a { color: #55ff55; }\n"
    "a:hover { color: #ffff55; background-color: #008000; }\n"
    "\n"
    "/* ── panels / cards ────────────────────────────────────────────── */\n"
    ".panel, .card {\n"
    "  border: double;\n"
    "  border-color: #55ffff;\n"
    "  padding: 8px;\n"
    "  margin-bottom: 8px;\n"
    "  background-color: #000055;\n"
    "}\n"
    "\n"
    ".panel-title, .card-title {\n"
    "  font-weight: bold;\n"
    "  color: #55ffff;\n"
    "}\n"
    "\n"
    "/* ── buttons ───────────────────────────────────────────────────── */\n"
    ".btn {\n"
    "  display: inline-block;\n"
    "  border: solid;\n"
    "  border-color: #aaaaaa;\n"
    "  padding: 8px;\n"
    "  color: #000000;\n"
    "  background-color: #aaaaaa;\n"
    "}\n"
    ".btn:hover {\n"
    "  background-color: #55ffff;\n"
    "  color: #000000;\n"
    "}\n"
    "\n"
    ".btn-primary {\n"
    "  background-color: #55ffff;\n"
    "  border-color: #55ffff;\n"
    "  color: #000080;\n"
    "}\n"
    ".btn-primary:hover {\n"
    "  background-color: #ffffff;\n"
    "}\n"
    "\n"
    ".btn-danger {\n"
    "  background-color: #ff5555;\n"
    "  border-color: #ff5555;\n"
    "  color: #ffffff;\n"
    "}\n"
    ".btn-danger:hover {\n"
    "  background-color: #ff0000;\n"
    "}\n"
    "\n"
    "/* ── tables ────────────────────────────────────────────────────── */\n"
    "table {\n"
    "  border-color: #55ffff;\n"
    "}\n"
    "th {\n"
    "  background-color: #000055;\n"
    "  color: #55ffff;\n"
    "  font-weight: bold;\n"
    "}\n"
    "td {\n"
    "  color: #ffff55;\n"
    "}\n"
    "\n"
    "/* ── alerts / status ───────────────────────────────────────────── */\n"
    ".alert {\n"
    "  border: solid;\n"
    "  padding: 8px;\n"
    "  margin-bottom: 8px;\n"
    "}\n"
    ".alert-info {\n"
    "  border-color: #55ffff;\n"
    "  color: #55ffff;\n"
    "  background-color: #000044;\n"
    "}\n"
    ".alert-success {\n"
    "  border-color: #55ff55;\n"
    "  color: #55ff55;\n"
    "  background-color: #003300;\n"
    "}\n"
    ".alert-warning {\n"
    "  border-color: #ffff55;\n"
    "  color: #ffff55;\n"
    "  background-color: #333300;\n"
    "}\n"
    ".alert-error {\n"
    "  border-color: #ff5555;\n"
    "  color: #ff5555;\n"
    "  background-color: #330000;\n"
    "}\n"
    "\n"
    "/* ── nav ───────────────────────────────────────────────────────── */\n"
    ".nav {\n"
    "  display: flex;\n"
    "  flex-direction: row;\n"
    "  gap: 16px;\n"
    "  border-bottom: solid;\n"
    "  border-color: #55ffff;\n"
    "  padding-bottom: 4px;\n"
    "  margin-bottom: 8px;\n"
    "}\n"
    "\n"
    "/* ── layout helpers ────────────────────────────────────────────── */\n"
    ".row { display: flex; flex-direction: row; gap: 8px; }\n"
    ".col { display: flex; flex-direction: column; gap: 8px; }\n"
    ".grow { flex-grow: 1; }\n"
    ".center { text-align: center; }\n"
    ".right { text-align: right; }\n"
    ".muted { color: #888888; }\n"
    ".bold { font-weight: bold; }\n"
    "\n"
    "/* ── hr ────────────────────────────────────────────────────────── */\n"
    "hr {\n"
    "  border-color: #55ffff;\n"
    "}\n"
    "\n"
    "/* ── code / pre ────────────────────────────────────────────────── */\n"
    "code { color: #55ff55; }\n"
    "pre {\n"
    "  border: solid;\n"
    "  border-color: #555555;\n"
    "  padding: 8px;\n"
    "  background-color: #000033;\n"
    "}\n"
    "\n"
    "/* ── form styling ──────────────────────────────────────────────── */\n"
    ".form-group {\n"
    "  display: block;\n"
    "  margin-bottom: 8px;\n"
    "}\n"
    ".form-label {\n"
    "  display: block;\n"
    "  color: #55ffff;\n"
    "  font-weight: bold;\n"
    "  margin-bottom: 4px;\n"
    "}\n"
    "\n";

const char* k_css_dark =
    "/* tvshow theme: dark\n"
    " * Modern dark theme — white on near-black, subtle borders.\n"
    " * Usage: <link rel=\"stylesheet\" href=\"/styles/dark.css\">\n"
    " */\n"
    "\n"
    "/* ── base ──────────────────────────────────────────────────────── */\n"
    "body {\n"
    "  color: #cccccc;\n"
    "  background-color: #1a1a1a;\n"
    "  padding: 8px;\n"
    "}\n"
    "\n"
    "/* ── headings ──────────────────────────────────────────────────── */\n"
    "h1 { color: #ffffff; }\n"
    "h2 { color: #dddddd; }\n"
    "h3 { color: #bbbbbb; }\n"
    "\n"
    "/* ── links ─────────────────────────────────────────────────────── */\n"
    "a { color: #6699ff; }\n"
    "a:hover { color: #99bbff; background-color: #333355; }\n"
    "\n"
    "/* ── panels / cards ────────────────────────────────────────────── */\n"
    ".panel, .card {\n"
    "  border: solid;\n"
    "  border-color: #444444;\n"
    "  padding: 8px;\n"
    "  margin-bottom: 8px;\n"
    "  background-color: #222222;\n"
    "}\n"
    "\n"
    ".panel-title, .card-title {\n"
    "  font-weight: bold;\n"
    "  color: #ffffff;\n"
    "}\n"
    "\n"
    "/* ── buttons ───────────────────────────────────────────────────── */\n"
    ".btn {\n"
    "  display: inline-block;\n"
    "  border: solid;\n"
    "  border-color: #555555;\n"
    "  padding: 8px;\n"
    "  color: #cccccc;\n"
    "  background-color: #333333;\n"
    "}\n"
    ".btn:hover {\n"
    "  background-color: #444444;\n"
    "  color: #ffffff;\n"
    "}\n"
    "\n"
    ".btn-primary {\n"
    "  background-color: #2255aa;\n"
    "  border-color: #2255aa;\n"
    "  color: #ffffff;\n"
    "}\n"
    ".btn-primary:hover {\n"
    "  background-color: #3366cc;\n"
    "}\n"
    "\n"
    ".btn-danger {\n"
    "  background-color: #aa2222;\n"
    "  border-color: #aa2222;\n"
    "  color: #ffffff;\n"
    "}\n"
    ".btn-danger:hover {\n"
    "  background-color: #cc3333;\n"
    "}\n"
    "\n"
    "/* ── tables ────────────────────────────────────────────────────── */\n"
    "table {\n"
    "  border-color: #444444;\n"
    "}\n"
    "th {\n"
    "  background-color: #2a2a2a;\n"
    "  color: #ffffff;\n"
    "  font-weight: bold;\n"
    "}\n"
    "td {\n"
    "  color: #cccccc;\n"
    "}\n"
    "\n"
    "/* ── alerts / status ───────────────────────────────────────────── */\n"
    ".alert {\n"
    "  border: solid;\n"
    "  padding: 8px;\n"
    "  margin-bottom: 8px;\n"
    "}\n"
    ".alert-info {\n"
    "  border-color: #336699;\n"
    "  color: #6699cc;\n"
    "  background-color: #1a2a3a;\n"
    "}\n"
    ".alert-success {\n"
    "  border-color: #338833;\n"
    "  color: #66cc66;\n"
    "  background-color: #1a2a1a;\n"
    "}\n"
    ".alert-warning {\n"
    "  border-color: #998833;\n"
    "  color: #cccc66;\n"
    "  background-color: #2a2a1a;\n"
    "}\n"
    ".alert-error {\n"
    "  border-color: #993333;\n"
    "  color: #cc6666;\n"
    "  background-color: #2a1a1a;\n"
    "}\n"
    "\n"
    "/* ── nav ───────────────────────────────────────────────────────── */\n"
    ".nav {\n"
    "  display: flex;\n"
    "  flex-direction: row;\n"
    "  gap: 16px;\n"
    "  border-bottom: solid;\n"
    "  border-color: #444444;\n"
    "  padding-bottom: 4px;\n"
    "  margin-bottom: 8px;\n"
    "}\n"
    "\n"
    "/* ── layout helpers ────────────────────────────────────────────── */\n"
    ".row { display: flex; flex-direction: row; gap: 8px; }\n"
    ".col { display: flex; flex-direction: column; gap: 8px; }\n"
    ".grow { flex-grow: 1; }\n"
    ".center { text-align: center; }\n"
    ".right { text-align: right; }\n"
    ".muted { color: #666666; }\n"
    ".bold { font-weight: bold; }\n"
    "\n"
    "/* ── hr ────────────────────────────────────────────────────────── */\n"
    "hr {\n"
    "  border-color: #444444;\n"
    "}\n"
    "\n"
    "/* ── code / pre ────────────────────────────────────────────────── */\n"
    "code { color: #66cc66; }\n"
    "pre {\n"
    "  border: solid;\n"
    "  border-color: #333333;\n"
    "  padding: 8px;\n"
    "  background-color: #111111;\n"
    "}\n"
    "\n"
    "/* ── form styling ──────────────────────────────────────────────── */\n"
    ".form-group {\n"
    "  display: block;\n"
    "  margin-bottom: 8px;\n"
    "}\n"
    ".form-label {\n"
    "  display: block;\n"
    "  color: #aaaaaa;\n"
    "  font-weight: bold;\n"
    "  margin-bottom: 4px;\n"
    "}\n"
    "\n";

const char* k_css_light =
    "/* tvshow theme: light\n"
    " * Light terminal theme — dark text on white/grey, clean borders.\n"
    " * Usage: <link rel=\"stylesheet\" href=\"/styles/light.css\">\n"
    " */\n"
    "\n"
    "/* ── base ──────────────────────────────────────────────────────── */\n"
    "body {\n"
    "  color: #222222;\n"
    "  background-color: #eeeeee;\n"
    "  padding: 8px;\n"
    "}\n"
    "\n"
    "/* ── headings ──────────────────────────────────────────────────── */\n"
    "h1 { color: #111111; }\n"
    "h2 { color: #222222; }\n"
    "h3 { color: #333333; }\n"
    "\n"
    "/* ── links ─────────────────────────────────────────────────────── */\n"
    "a { color: #0055aa; }\n"
    "a:hover { color: #003377; background-color: #ccddee; }\n"
    "\n"
    "/* ── panels / cards ────────────────────────────────────────────── */\n"
    ".panel, .card {\n"
    "  border: solid;\n"
    "  border-color: #aaaaaa;\n"
    "  padding: 8px;\n"
    "  margin-bottom: 8px;\n"
    "  background-color: #ffffff;\n"
    "}\n"
    "\n"
    ".panel-title, .card-title {\n"
    "  font-weight: bold;\n"
    "  color: #111111;\n"
    "}\n"
    "\n"
    "/* ── buttons ───────────────────────────────────────────────────── */\n"
    ".btn {\n"
    "  display: inline-block;\n"
    "  border: solid;\n"
    "  border-color: #999999;\n"
    "  padding: 8px;\n"
    "  color: #222222;\n"
    "  background-color: #dddddd;\n"
    "}\n"
    ".btn:hover {\n"
    "  background-color: #cccccc;\n"
    "  color: #000000;\n"
    "}\n"
    "\n"
    ".btn-primary {\n"
    "  background-color: #0055aa;\n"
    "  border-color: #0055aa;\n"
    "  color: #ffffff;\n"
    "}\n"
    ".btn-primary:hover {\n"
    "  background-color: #004488;\n"
    "}\n"
    "\n"
    ".btn-danger {\n"
    "  background-color: #cc2222;\n"
    "  border-color: #cc2222;\n"
    "  color: #ffffff;\n"
    "}\n"
    ".btn-danger:hover {\n"
    "  background-color: #aa1111;\n"
    "}\n"
    "\n"
    "/* ── tables ────────────────────────────────────────────────────── */\n"
    "table {\n"
    "  border-color: #999999;\n"
    "}\n"
    "th {\n"
    "  background-color: #dddddd;\n"
    "  color: #111111;\n"
    "  font-weight: bold;\n"
    "}\n"
    "td {\n"
    "  color: #222222;\n"
    "}\n"
    "\n"
    "/* ── alerts / status ───────────────────────────────────────────── */\n"
    ".alert {\n"
    "  border: solid;\n"
    "  padding: 8px;\n"
    "  margin-bottom: 8px;\n"
    "}\n"
    ".alert-info {\n"
    "  border-color: #4488cc;\n"
    "  color: #224488;\n"
    "  background-color: #ddeeff;\n"
    "}\n"
    ".alert-success {\n"
    "  border-color: #44aa44;\n"
    "  color: #226622;\n"
    "  background-color: #ddeedd;\n"
    "}\n"
    ".alert-warning {\n"
    "  border-color: #ccaa33;\n"
    "  color: #886600;\n"
    "  background-color: #ffeecc;\n"
    "}\n"
    ".alert-error {\n"
    "  border-color: #cc4444;\n"
    "  color: #882222;\n"
    "  background-color: #ffdddd;\n"
    "}\n"
    "\n"
    "/* ── nav ───────────────────────────────────────────────────────── */\n"
    ".nav {\n"
    "  display: flex;\n"
    "  flex-direction: row;\n"
    "  gap: 16px;\n"
    "  border-bottom: solid;\n"
    "  border-color: #aaaaaa;\n"
    "  padding-bottom: 4px;\n"
    "  margin-bottom: 8px;\n"
    "}\n"
    "\n"
    "/* ── layout helpers ────────────────────────────────────────────── */\n"
    ".row { display: flex; flex-direction: row; gap: 8px; }\n"
    ".col { display: flex; flex-direction: column; gap: 8px; }\n"
    ".grow { flex-grow: 1; }\n"
    ".center { text-align: center; }\n"
    ".right { text-align: right; }\n"
    ".muted { color: #888888; }\n"
    ".bold { font-weight: bold; }\n"
    "\n"
    "/* ── hr ────────────────────────────────────────────────────────── */\n"
    "hr {\n"
    "  border-color: #aaaaaa;\n"
    "}\n"
    "\n"
    "/* ── code / pre ────────────────────────────────────────────────── */\n"
    "code { color: #006600; }\n"
    "pre {\n"
    "  border: solid;\n"
    "  border-color: #cccccc;\n"
    "  padding: 8px;\n"
    "  background-color: #f5f5f5;\n"
    "}\n"
    "\n"
    "/* ── form styling ──────────────────────────────────────────────── */\n"
    ".form-group {\n"
    "  display: block;\n"
    "  margin-bottom: 8px;\n"
    "}\n"
    ".form-label {\n"
    "  display: block;\n"
    "  color: #444444;\n"
    "  font-weight: bold;\n"
    "  margin-bottom: 4px;\n"
    "}\n"
    "\n";

}  // namespace tvshow::app
